version: '3.4'

services:
  shortlinkdb:
    image: postgres
    container_name: shortlinkdb
    ports: 
    -  5432:5432
    restart: always
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  shorturllinkapi:
    image: shorturllinkapi
    container_name: shorturllinkapihost
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    links: 
      - shortlinkdb
    depends_on: [shortlinkdb]
        
